import Navbar from '@/components/ui/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The New Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='min-h-screen'>
      <body className={`${inter.className} relative flex flex-col`}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
